/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de11;

import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author ndthi
 */
public class Client extends javax.swing.JFrame {

    public static int soN;
    /**
     * Creates new form Client
     */
    public Client() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fcpath = new javax.swing.JFileChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtcontent1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtcontent2 = new javax.swing.JTextArea();
        btndocvanban = new javax.swing.JButton();
        btnghivanban = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtpath = new javax.swing.JTextField();
        btnchon = new javax.swing.JButton();
        btnrandom = new javax.swing.JButton();
        btnsendserver = new javax.swing.JButton();
        txtport = new javax.swing.JTextField();
        txtip = new javax.swing.JTextField();
        txtson = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtcontent1.setColumns(20);
        txtcontent1.setRows(5);
        jScrollPane2.setViewportView(txtcontent1);

        txtcontent2.setColumns(20);
        txtcontent2.setRows(5);
        jScrollPane3.setViewportView(txtcontent2);

        btndocvanban.setText("Đọc File văn bản");
        btndocvanban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndocvanbanActionPerformed(evt);
            }
        });

        btnghivanban.setText("Ghi File văn bản");
        btnghivanban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnghivanbanActionPerformed(evt);
            }
        });

        jLabel1.setText("Chọn đường dẫn");

        btnchon.setText("Chọn");
        btnchon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchonActionPerformed(evt);
            }
        });

        btnrandom.setText("Ngẫu Nhiên");
        btnrandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrandomActionPerformed(evt);
            }
        });

        btnsendserver.setText("Gửi");
        btnsendserver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendserverActionPerformed(evt);
            }
        });

        txtport.setText("5432");

        txtip.setText("localhost");

        jLabel2.setText("Số lượng ps ngẫu nhiên");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnsendserver)
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtip, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(txtport, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnrandom, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtpath, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnchon, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnghivanban)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btndocvanban)
                                .addGap(15, 15, 15))))
                    .addComponent(txtson, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtpath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnchon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnrandom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnsendserver)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndocvanban)
                    .addComponent(btnghivanban))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndocvanbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndocvanbanActionPerformed
        // TODO add your handling code here:
//        try {
//            FileReader fr = new FileReader(new File(txtpath.getText()));
//            StringBuffer sb = new StringBuffer();
//            char ca[] = new char[5];
//            while (fr.ready()) {
//                int leng = fr.read(ca);
//                sb.append(ca, 0, leng);
//            }
//            fr.close();
//            txtcontent1.setText(sb + "");
//
//            ArrayList<String> mauso = new ArrayList<String>();
//            String a = sb.toString();
//            for (int i = 0; i < 10 ; i++) {
//                String[] parts = a.split("\\n");
//                String mau = parts[i];//split lấy trước enter
//                System.out.println(mau);
//                mauso.add(mau);
//            }
//
//            ArrayList<String> psnguyento = new ArrayList<String>();
//            ArrayList<String> pskhongnguyento = new ArrayList<String>();
//            SoNguyenTo snt = new SoNguyenTo();
//            String maus = null;
//            for (int i = 0; i < mauso.size(); i++) {
//                String[] b = mauso.get(i).split("/");
//                maus = b[1];
//                if ((Integer.parseInt(maus)) >1 &&snt.kiemtranguyento(Integer.parseInt(maus)) == true) {
//                    psnguyento.add(mauso.get(i)+"\n");
//                } else {
//                    pskhongnguyento.add(mauso.get(i)+"\n");
//
//                }
//            }
//            String custompsnguyento = psnguyento.toString();
//            custompsnguyento = custompsnguyento.substring(1, custompsnguyento.length() - 1).replaceAll(",","").replaceAll(" ","");
//            txtcontent1.setText("Các phân số có mẫu\n là nguyên tố:\n"+custompsnguyento);
//            String custompsknguyento = pskhongnguyento.toString();
//            custompsknguyento = custompsknguyento.substring(1, custompsknguyento.length() - 1).replaceAll(",","").replaceAll(" ","");
//            txtcontent2.setText("Các phân số có mẫu\nkhông là nguyên tố:\n"+custompsknguyento);
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//        JOptionPane.showMessageDialog(null, "thanh cong");
    }//GEN-LAST:event_btndocvanbanActionPerformed

    private void btnghivanbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnghivanbanActionPerformed
        //         TODO add your handling code here:
//        try {
//
//            FileWriter fw = new FileWriter(new File(txtpath.getText()));
//            fw.write(txtcontent1.getText());
//            fw.close();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//        JOptionPane.showMessageDialog(null, "thanh cong");
    }//GEN-LAST:event_btnghivanbanActionPerformed

    private void btnchonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchonActionPerformed
        // TODO add your handling code here:
        this.fcpath.setVisible(true);
        fcpath.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        if (this.fcpath.showOpenDialog(this) == JFileChooser.APPROVE_OPTION);
        {
            try {
                txtpath.setText(fcpath.getSelectedFile().getCanonicalPath());
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_btnchonActionPerformed

    private void btnrandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrandomActionPerformed
        // TODO add your handling code here:
        ArrayList<String> phanso = new ArrayList<String>();
        for (int i = 0; i < Integer.parseInt(txtson.getText()); i++) {
            Random rand = new Random();
            int tuso =1+ rand.nextInt(100) ;
            int mauso =1+ rand.nextInt(100) ;
            phanso.add(tuso + "/" + mauso + "\n");
        }
        String customphanso = phanso.toString();
        customphanso = customphanso.substring(1, customphanso.length() - 1);
        customphanso = customphanso.replaceAll(" ", "");
        txtcontent1.setText(customphanso.replaceAll(",", ""));

        txtcontent2.setText("");
        soN = Integer.parseInt(txtson.getText());
        System.out.println(soN);
    }//GEN-LAST:event_btnrandomActionPerformed

    private void btnsendserverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendserverActionPerformed
        try {
            
                
            
            DatagramSocket datagramSocket = new DatagramSocket();
     
            // TODO add your handling code here:
            
            byte[] readPsnt = new byte[1024];// vì cần nhận 2 số từ server và gửi 1 số
            byte[] readPsknt = new byte[1024];
            byte[] writeRandom = new byte[1024];
            
            InetAddress host = InetAddress.getByName(txtip.getText()); // khai báo cổng và ip
            int port = Integer.parseInt(txtport.getText());
            
            String random = txtcontent1.getText();
            writeRandom = random.getBytes(); // ép kiểu string -> byte
            DatagramPacket sendRandom = new DatagramPacket(writeRandom, writeRandom.length, host, port);
            
            datagramSocket.send(sendRandom);
            txtcontent1.setText("");
            
            DatagramPacket receivepsnt = new DatagramPacket(readPsnt, readPsnt.length);
            datagramSocket.receive(receivepsnt);
            String psnt = new String(receivepsnt.getData());
            System.out.println(psnt);
            txtcontent1.setText(psnt);
            
            DatagramPacket receivepsknt = new DatagramPacket(readPsknt, readPsknt.length);
            datagramSocket.receive(receivepsknt);
            String psknt = new String(receivepsknt.getData());
            System.out.println(psknt);
            txtcontent2.setText(psknt);
            datagramSocket.close();
            
         
        } catch (IOException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsendserverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchon;
    private javax.swing.JButton btndocvanban;
    private javax.swing.JButton btnghivanban;
    private javax.swing.JButton btnrandom;
    private javax.swing.JButton btnsendserver;
    private javax.swing.JFileChooser fcpath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtcontent1;
    private javax.swing.JTextArea txtcontent2;
    private javax.swing.JTextField txtip;
    private javax.swing.JTextField txtpath;
    private javax.swing.JTextField txtport;
    private javax.swing.JTextField txtson;
    // End of variables declaration//GEN-END:variables
}
