/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de11;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.util.ArrayList;
import java.util.Base64;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author ndthi
 */
public class Server extends javax.swing.JFrame {

    boolean kiemtranguyento(int n) {
        for (int i = 2; i <= Math.sqrt(n); i++) {
            if (n % i == 0) {
                return false;
            }
        }
        return true;
    }

    /**
     * Creates new form Server
     */
    public Server() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fcpath = new javax.swing.JFileChooser();
        txtconnect = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtcontent1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtcontent2 = new javax.swing.JTextArea();
        btnchon = new javax.swing.JButton();
        txtpath = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        txtkey = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtconnect.setText("Connect");
        txtconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconnectActionPerformed(evt);
            }
        });

        txtcontent1.setColumns(20);
        txtcontent1.setRows(5);
        jScrollPane1.setViewportView(txtcontent1);

        txtcontent2.setColumns(20);
        txtcontent2.setRows(5);
        jScrollPane2.setViewportView(txtcontent2);

        btnchon.setText("Chọn");
        btnchon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchonActionPerformed(evt);
            }
        });

        jLabel1.setText("Chọn đường dẫn");

        jTextField1.setText("Khoá");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(txtconnect))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtpath, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnchon, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtkey, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtpath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnchon))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtkey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(txtconnect)
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconnectActionPerformed
        // TODO add your handling code here:
        try {

            while (true) {

//                String SECRET_KEY = txtkey.getText();
//                SecretKeySpec skeySpec = new SecretKeySpec(SECRET_KEY.getBytes(), "DES");

                DatagramSocket datagramSocket = new DatagramSocket(5432);

                // đưa này vào trong while
                byte[] readRandom = new byte[1024];
                byte[] writePsnt = new byte[1024];
                byte[] writePsknt = new byte[1024];

                DatagramPacket receivePacket = new DatagramPacket(readRandom, readRandom.length);

                datagramSocket.receive(receivePacket);

                String line = new String(receivePacket.getData()).trim();
//                String line2 = new String(receivePacket1.getData()).trim();
//                String kqMul = new String(receivePacket2.getData()).trim();
//                txta.setText(line);
//                txtb.setText(line2);
//                txtKQMul.setText(kqMul);
                txtcontent1.setText(line);
                System.out.println(line);

//                Cipher cipher = Cipher.getInstance("DES/ECB/PKCS5PADDING");//mã hoá
//                cipher.init(Cipher.ENCRYPT_MODE, skeySpec);
//                byte[] byteEncrypted = cipher.doFinal(txtcontent1.getText().getBytes());
//                String encrypted = Base64.getEncoder().encodeToString(byteEncrypted);
//                System.out.println(encrypted);

//                cipher.init(Cipher.DECRYPT_MODE, skeySpec);
//                byte[] byteDecrypted = cipher.doFinal(byteEncrypted);
//                String decrypted = new String(byteDecrypted);

                ChucNang chucNang = new ChucNang();
                chucNang.ghiFile(txtpath.getText(), txtcontent1.getText());
                chucNang.docFile(txtpath.getText(), txtcontent1.getText(), txtcontent2.getText());
                txtcontent1.setText(chucNang.content1);
                txtcontent2.setText(chucNang.content2);

//                System.out.println("dữ liệu nhận: " + line);
//                System.out.println("dữ liệu nhận: " + line2);
//                System.out.println("dữ liệu nhận: " + kqMul);
//                // bỏ cái writeBuffer này
//                //writeBuffer = line.getBytes();
//
                InetAddress host = receivePacket.getAddress();
                int port = receivePacket.getPort();

                String psnt = txtcontent1.getText();
                writePsnt = psnt.getBytes(); // ép kiểu string -> byte
//
                DatagramPacket sendpsnt = new DatagramPacket(writePsnt, writePsnt.length, host, port);
                datagramSocket.send(sendpsnt);

                String psknt = txtcontent2.getText();
                writePsnt = psknt.getBytes(); // ép kiểu string -> byte
//
                DatagramPacket sendpsknt = new DatagramPacket(writePsnt, writePsnt.length, host, port);
                datagramSocket.send(sendpsknt);
//
//                DatagramPacket sendPacket1 = new DatagramPacket(writeBuffer1, writeBuffer1.length, host, port);
//                datagramSocket.send(sendPacket1);
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtconnectActionPerformed

    private void btnchonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchonActionPerformed
        // TODO add your handling code here:
        this.fcpath.setVisible(true);
        fcpath.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        if (this.fcpath.showOpenDialog(this) == JFileChooser.APPROVE_OPTION);
        {
            try {
                txtpath.setText(fcpath.getSelectedFile().getCanonicalPath());
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_btnchonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchon;
    private javax.swing.JFileChooser fcpath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton txtconnect;
    private javax.swing.JTextArea txtcontent1;
    private javax.swing.JTextArea txtcontent2;
    private javax.swing.JTextField txtkey;
    private javax.swing.JTextField txtpath;
    // End of variables declaration//GEN-END:variables
}
